# POC values for WSO2 IS deployment
# Aligned to the Helm chart value structure in `kubernetes-is/values.yaml`.

wso2:
  subscription:
    username: ""
    password: ""

deployment:
  image:
    registry: "docker.wso2.com"
    repository: "wso2is"
    digest: ""
    tag: "7.0.0"
    pullPolicy: IfNotPresent
    imagePullSecret: ""

  replicas: 1

  resources:
    requests:
      memory: "1Gi"
      cpu: "1000m"
    limits:
      memory: "2Gi"
      cpu: "2000m"
    jvm:
      memOpts: "-Xms1024m -Xmx1024m"

  persistence:
    enabled: false

  ingress:
    hostName: "is.local"
    ingressClassName: "nginx"
    tlsSecretsName: "is-tls"
    enableNginxRateLimit: false

deploymentToml:
  database:
    identity:
      type: "mysql"
      url: "jdbc:mysql://mysql.wso2.svc.cluster.local:3306/WSO2IS_IDENTITY_DB?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true"
      username: "wso2carbon"
      password: "wso2carbon"
      driver: "com.mysql.cj.jdbc.Driver"
    shared:
      type: "mysql"
      url: "jdbc:mysql://mysql.wso2.svc.cluster.local:3306/WSO2IS_SHARED_DB?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true"
      username: "wso2carbon"
      password: "wso2carbon"
      driver: "com.mysql.cj.jdbc.Driver"
    user:
      type: "mysql"
      url: "jdbc:mysql://mysql.wso2.svc.cluster.local:3306/WSO2IS_SHARED_DB?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true"
      username: "wso2carbon"
      password: "wso2carbon"
      driver: "com.mysql.cj.jdbc.Driver"
    consent:
      type: "mysql"
      url: "jdbc:mysql://mysql.wso2.svc.cluster.local:3306/WSO2IS_IDENTITY_DB?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true"
      username: "wso2carbon"
      password: "wso2carbon"
      driver: "com.mysql.cj.jdbc.Driver"
